import pywhatkit as kit
import pandas as pd
import time

# 1. Read your contacts from the CSV file generated by invite-generator.html
# Make sure to fill in the empty 'Phone' column in contacts.csv first!
print("Reading contacts.csv...")
try:
    df = pd.read_csv('contacts.csv')
except FileNotFoundError:
    print("Error: contacts.csv not found. Please export it from the Generator and ensure it is in the same folder.")
    exit()

print(f"Loaded {len(df)} contacts. Starting WhatsApp bulk sender...")

# 2. Loop through each person
for index, row in df.iterrows():
    # Ensure phone number is valid
    if pd.isna(row['Phone']) or str(row['Phone']).strip() == "":
        print(f"Skipping {row['Name']} - No phone number provided in CSV.")
        continue
        
    phone_number = str(row['Phone']).strip()
    
    # If the phone number lacks a '+' symbol, it might cause issues, but pywhatkit usually requires country code
    if not phone_number.startswith('+'):
        print(f"Warning: Phone number {phone_number} for {row['Name']} is missing a '+' country code. It might fail.")

    name = row['Name']
    invite_url = row['URL']
    
    # 3. Create the customized message template
    message = (
        f"Assalamu Alaikum {name},\n\n"
        f"You are cordially invited to the Nikkah of\n"
        f"*Mofitha & Mohamed Nowsath Ali*\n"
        f"on Sunday, 3rd May 2026.\n\n"
        f"Your personal invitation:\n{invite_url}"
    )
    
    print(f"\nPreparing to send to {name} ({phone_number})...")
    
    try:
        # 4. Send the message instantly
        # Parameters: phone_no, message, wait_time, tab_close, close_time
        # wait_time=15 allows WhatsApp web to load
        kit.sendwhatmsg_instantly(
            phone_no=phone_number,
            message=message,
            wait_time=15,
            tab_close=True,
            close_time=4
        )
        print(f"✅ Successfully sent to {name}")
        
        # 5. Wait to prevent spam bans (15 seconds)
        print("Waiting 15 seconds to prevent spam detectors...")
        time.sleep(15) 
        
    except Exception as e:
        print(f"❌ Failed to send to {name}: {e}")

print("\n🎉 All messages have been processed!")
